[files]
extend-exclude = [
    "docs/nl/",
    "docs/.vitepress/nl.ts",
    "docs/pt/",
    "docs/.vitepress/pt.ts",
    "docs/zh_cn/",
    "docs/.vitepress/zh_cn.ts",
    "docs/de/",
    "docs/.vitepress/de.ts",
    "docs/vi/",
    "docs/.vitepress/vi.ts",
]
